### ISSUE TITLE
Volume Bar is displayed only when audio is played on another device

### ISSUE THREAD

**Issue by Toff-kun** [janch32/Spotify-WPW#13]
I'm not sure if this is an intended behavior, but it's somewhat confusing. Volume bar only shows up under Connect device picker when audio is played on a device other than the one you currently use. This also makes it impossible to change the volume directly from the device for which the volume was modified.

![image](https://user-images.githubusercontent.com/10385850/56871662-922ae980-6a29-11e9-84fc-6db46b0dcf64.png)

![image](https://user-images.githubusercontent.com/10385850/56871665-9ce57e80-6a29-11e9-8066-0fefeef26170.png)

**Comment by janchaloupka** [comment]
Yes it is intended, but I agree that it's confusing. 

If you look into script.js, you will see that I tried to make the volume fixed on 100% when the audio is playing on mobile but I abandoned the idea and I forgot to change the visibility of the volume slider back.
