### ISSUE TITLE
Spotify no longer supports mobile MSEdge (end of this app?)

### ISSUE THREAD

**Issue by janchaloupka** [janch32/Spotify-WPW#15]
I've been notified that the Spotify web player now shows warning message about unsupported browser version.

![wp_ss_20190517_0002](https://user-images.githubusercontent.com/7803688/57941339-f1647700-78ce-11e9-9c9a-36f069c944af.png)

The app still works for now - the only difference is the warning message. But it's only matter of time until they add new features that will not work with the (old) mobile Microsoft Edge and I don't think that this is something that can be fixed.

So once they change something critical it will be the end for this app 🙁.

**Comment by Toff-kun** [comment]
I wonder if it actually means anything. Not like this version of Edge was well-supported in the first place. We'll see.

**Comment by janchaloupka** [comment]
I wanted to remove themessage but it won't pop up on desktop and the inspect element doesn't work when the app is debugged on mobile (this is a known UWP limitation).

**Comment by janchaloupka** [comment]
Warning message removed in pull request #16

**Comment by janchaloupka** [comment]
I just published release 2.0.4.0 with the warning message removed to the store, so it should be updated in about a week.
