### ISSUE TITLE
Podcast episode dates display square placeholders

### ISSUE THREAD

**Issue by Toff-kun** [janch32/Spotify-WPW#3]
Happens to emojis as well.

Maybe using font fallback should help, as described in this article: 
https://support.microsoft.com/en-us/help/3083806/why-does-some-text-display-with-square-boxes-in-some-apps-on-windows-1

![image](https://user-images.githubusercontent.com/10385850/54082665-dd762500-4321-11e9-9bce-7eba8dff38ed.png)

**Comment by janchaloupka** [comment]
Fixed in 2.0.0.0 release
