### ISSUE TITLE
No custom styles applied on Lumia 535

### ISSUE THREAD

**Issue by janchaloupka** [janch32/Spotify-WPW#4]
**Device:** Microsoft Lumia 535
**OS version:** 1607 (14393.2551)
**Resolution:** Default (150%)

App fails to apply custom styles. I'm not sure what causes it, but it looks like it tries to make changes to element before it even exists which is strange, because the function is supposed to run after the page has been loaded. 
I cannot reproduce it anywhere else (all emulators + lumia640 are okay)

### Screenshot ###
![wp_ss_20190310_0001](https://user-images.githubusercontent.com/7803688/54090680-ec3af700-4376-11e9-83d4-b7fbe9a17daa.png)

**Comment by Toff-kun** [comment]
Is your Lumia 640 running Creators Update or higher? My guess is that this bug is a result of the lack of CSS custom properties (--*) support in Anniversary Update, which were added to Edge only with Creators Update.

**Comment by janchaloupka** [comment]
Yes, I believe the Lumia 640 is on Fall Creators Update (i have insiders version installed). But I don't think that the lack of variables should completely break the layout, the rendering engine just skips unknown properties.

**Comment by Tourniquet88** [comment]
Device: Microsoft Lumia 730
OS version: 1607 (14393.2551)
Resolution: Default (200%)

I can confirm the same thing on my Lumia 730. So it must be releated to the Anniversay Update I guess.

**Comment by janchaloupka** [comment]
I maybe found out what's causing it. For some reason on anniversary update cannot load local file (with ms-appx-web) on https-enabled site. The debug options for webview on physical device are extremely limited so I can't say what exactly prevents the file from loading and why it's different with the Creators update.

**Comment by Toff-kun** [comment]
Does it work with a direct https link to the style.css instead of ms-appx-web?

**Comment by janchaloupka** [comment]
Yes, the style loads correctly over https protocol (I loaded the file on my webserver https://janchaloupka.cz/SpotifyWebWrapper/style.css), But you cannot load local app files with https.

Microsoft Store does not have any metric to show what percentage of users are on 1607 or lower. That means I don't know how widespread this issue is.

**Comment by Tourniquet88** [comment]
Is there any chance you can work around for 1607? I still prefer that Version of Mobile to any 15063/15254 Build. In my opinion 14393 is the most stable release for Mobile.

**Comment by janchaloupka** [comment]
Yes, I can fix it by chaging how the styles are loaded, it just wasn't at the top of my priority list because i didn't think anyone is using this version and nobody complained.

Now the styles are loaded with custom javascript directly from the web page, but I can load the styles in the app and then send the styles in a string to the webview. It's a bit of work but it's certainly possible.

**Comment by Tourniquet88** [comment]
You should be able to see how many people actually use 1607 though in the Developer Dashboard. I often see people saying they still are using 1607. Mainly because their phones didn't get 1703 or above: 
 Lumia Icon, 1520, 930, 730, 735, 830, 532, 535, 540, 635 1GB, 636 1GB, 638 1GB, 430, 435, BLU Win HD w510u, BLU Win HD LTE x150q

Actually I even see some people still using 1511.

**Comment by janchaloupka** [comment]
I can't find anything about usage by os version, I only see usage by app version and if they are on mobile/PC.

These are all the options i can see, and the "devices" tab are grouped by version release
![image](https://user-images.githubusercontent.com/7803688/58025113-02ea9080-7b14-11e9-80e0-37c931d77847.png)

**Comment by janchaloupka** [comment]
Hello @Toff-kun, I saw your post on /r/windowsphone and you said that you fixed the anniversary update bug, can you please push the fix so I can upload it to the store?

**Comment by Toff-kun** [comment]
Oh, I didn't fix it, I just use a remote style in the script instead of the local one, uploaded to archive.org. It's hardly a solution, but works for testing.
