### ISSUE TITLE
Active navigation menu buttons cannot be pressed again

### ISSUE THREAD

**Issue by Toff-kun** [janch32/Spotify-WPW#8]
This becomes an issue when Now Playing Bar is expanded, and so in order to minimize it back to a Compact Playing Bar it is necessary to click the button other than the currently active one.

**Comment by janchaloupka** [comment]
You can close the expanded music controls using the back button. But i sort of fixed it in next release, because the music controls will take up the entire screen height when expanded.

**Comment by Toff-kun** [comment]
I played around with it and managed to make it open fullscreen at some point to make it follow the original screenshots closer, but relying solely on the back button (which is a software button on a panel that I normally hide on a 950XL) to minimize it was a bit inconvenient. It would be nice to also make it possible to minimize it by tapping somewhere once it's expanded.

**Comment by janchaloupka** [comment]
Fixed in release 2.0.0.0
